Repository dnd-side-project/dnd-13th-8-frontend, pull requests merged in 2025-08, with the labels that each got.

#5 [chore] yarn에서 pnpm으로 패키지 매니저 변경
  .coderabbit.yaml
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: CRITICAL

#9 [chore] ci/cd 워크플로우 작성
  .github/workflows/auto-sync-fork.yml
  .github/workflows/pr-check.yml
  .gitignore
  pnpm-lock.yaml
Labels: MEDIUM

#12 [chore] Global theme 설정
  eslint.config.js
  src/app/providers/ThemeProvider.tsx
  src/shared/styles/globalStyle.ts
  src/shared/styles/theme.ts
  src/shared/types/theme.ts
Labels: CRITICAL

#18 [feat] 버튼 컴포넌트 구현
  src/shared/styles/theme.ts
  src/shared/ui/Button.tsx
  src/stories/Button.stories.ts
Labels: HIGH

#22 [feat] playlist 컴포넌트 구현
  src/assets/icons/icn_gallery.svg
  src/assets/icons/icn_like.svg
  src/assets/icons/index.ts
  src/assets/images/img_cd_base.png
  src/assets/images/img_cd_overlay_test.png
  src/shared/ui/Cd.tsx
  src/shared/ui/Link.tsx
  src/stories/Link.stories.ts
  src/stories/Playlist.stories.tsx
  src/stories/PlaylistWithSong.stories.ts
  src/widgets/playlist/Playlist.tsx
  src/widgets/playlist/PlaylistWithSong.tsx
Labels: HIGH

#23 [feat] 홈페이지 상단 캐러셀, Badge 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/assets/images/img_character.png
  src/pages/homePage/ui/DotButton.tsx
  src/pages/homePage/ui/TopCarousel.tsx
  src/shared/styles/commonStyle.ts
  src/shared/styles/mixins.ts
  src/shared/ui/Badge.tsx
  src/stories/Badge.stories.ts
  src/stories/TopCarousel.stories.tsx
Labels: HIGH

#30 [feat] Modal, Profile 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/assets/images/img_profile.png
  src/assets/images/index.ts
  src/shared/styles/mixins.ts
  src/shared/ui/Modal.tsx
  src/shared/ui/Overlay.tsx
  src/shared/ui/Profile.tsx
  src/stories/Modal.stories.tsx
  src/stories/Profile.stories.tsx
Labels: HIGH

#27 [feat] Content Header, Input 컴포넌트 구현
  .gemini/styleguide.md
  pnpm-lock.yaml
  src/App.tsx
  src/assets/icons/icn_filter.svg
  src/assets/icons/icn_search.svg
  src/assets/icons/icn_send.svg
  src/assets/icons/index.ts
  src/pages/homePage/ui/DotButton.tsx
  src/pages/homePage/ui/TopCarousel.tsx
  src/shared/hooks/useDevice.ts
  src/shared/hooks/useHook.ts
  src/shared/hooks/useSort.ts
  src/shared/styles/globalStyle.ts
  src/shared/ui/Badge.tsx
  src/shared/ui/BottomSheet.tsx
  src/shared/ui/Button.tsx
  src/shared/ui/ContentHeader.tsx
  src/shared/ui/Input.tsx
  src/shared/ui/Overlay.tsx
  src/shared/ui/SvgButton.tsx
  src/stories/BottomSheet.stories.tsx
  src/stories/ContentHeader.stories.tsx
  src/stories/Input.stories.ts
Labels: HIGH

#33 [feat] ScrollCarousel 컴포넌트 구현
  src/shared/ui/ScrollCarousel.tsx
  src/stories/ScrollCarousel.stories.tsx
Labels: HIGH

#35 [style] TopCarousel 디자인 수정사항 반영
  src/pages/homePage/config/messages.ts
  src/pages/homePage/ui/LoopCarousel.tsx
  src/shared/ui/Badge.tsx
  src/shared/ui/Button.tsx
  src/stories/LoopCarousel.stories.tsx
Labels: HIGH

#39 [feat] 마이페이지 > MY 앨범, MY 좋아요, 내 정보 관리 UI 구현
  package.json
  src/App.tsx
  src/app/routes/routes.tsx
  src/assets/icons/icn_camera.svg
  src/assets/icons/icn_plus.svg
  src/assets/icons/index.ts
  src/entities/user/model/useAuth.ts
  src/entities/user/model/userStore.ts
  src/pages/myPage/mock/likePlaylist.json
  src/pages/myPage/mock/myPlaylist.json
  src/pages/myPage/ui/components/Divider.tsx
  src/pages/myPage/ui/components/PlaylistGrid.tsx
  src/pages/myPage/ui/components/UserProfile.tsx
  src/pages/myPage/ui/components/index.ts
  src/pages/myPage/ui/index.tsx
  src/pages/myPage/ui/ui.tsx
  src/shared/config/navItems.ts
  src/shared/hooks/useSingleSelect.ts
  src/shared/hooks/useSort.ts
  src/shared/styles/theme.ts
  src/shared/ui/BottomSheet.tsx
  src/shared/ui/ContentHeader.tsx
  src/shared/ui/Header.tsx
  src/shared/ui/Input.tsx
  src/shared/ui/Loading.tsx
  src/shared/ui/NavBar.tsx
  src/shared/ui/Profile.tsx
  src/shared/ui/index.ts
  src/stories/ContentHeader.stories.tsx
  src/stories/Input.stories.ts
  src/stories/Loading.stories.tsx
  src/widgets/authGuard/PrivateRoute.tsx
Labels: HIGH

#44 [feat] 검색 페이지 UI 구현
  src/app/routes/routes.tsx
  src/pages/homePage/index.tsx
  src/pages/homePage/ui/index.ts
  src/pages/searchPage/SearchResultPage.tsx
  src/pages/searchPage/index.tsx
  src/pages/searchPage/ui/SearchResultItem.tsx
  src/pages/searchPage/ui/TrendKeyword.tsx
  src/pages/searchPage/ui/index.ts
  src/shared/config/navItems.ts
  src/shared/ui/CategoryButton.tsx
  src/shared/ui/Header.tsx
  src/shared/ui/Input.tsx
  src/shared/ui/NavBar.tsx
  src/shared/ui/index.ts
  src/stories/CategoryButton.stories.tsx
  src/stories/SearchResultItem.stories.tsx
  src/stories/TrendKeyword.stories.ts
  src/widgets/playlist/index.ts
Labels: HIGH

#49 [feat] 마이페이지 > 플레이리스트 추가 UI 구현
  src/assets/icons/icn_down_arrow.svg
  src/assets/icons/icn_drag.svg
  src/assets/icons/icn_help_circle.svg
  src/assets/icons/icn_pencil_primary.svg
  src/assets/icons/icn_pin.svg
  src/assets/icons/icn_pin_primary.svg
  src/assets/icons/icn_share.svg
  src/assets/icons/icn_trash.svg
  src/assets/icons/index.ts
  src/pages/customize/index.tsx
  src/pages/myPage/ui/components/PlaylistGrid.tsx
  src/pages/myPage/ui/create/index.tsx
  src/shared/config/musicGenres.ts
  src/shared/config/routesConfig.ts
  src/shared/ui/Button.tsx
Labels: HIGH

#48 [feat] 둘러보기 UI 구현
  src/assets/icons/icn_heart.svg
  src/assets/icons/icn_mark.svg
  src/assets/icons/icn_next.svg
  src/assets/icons/icn_playlist.svg
  src/assets/icons/icn_prev.svg
  src/assets/icons/icn_start.svg
  src/assets/icons/icn_user.svg
  src/assets/icons/icn_watermark.svg
  src/assets/icons/index.ts
  src/pages/discoverPage/PlaylistInfoPage.tsx
  src/pages/discoverPage/index.tsx
  src/pages/discoverPage/mockData.json
  src/shared/config/routesConfig.ts
  src/shared/styles/globalStyle.ts
  src/shared/styles/theme.ts
  src/shared/ui/BottomSheet.tsx
  src/shared/ui/Header.tsx
  src/shared/ui/LiveInfo.tsx
  src/shared/ui/NavBar.tsx
  src/shared/ui/SvgButton.tsx
  src/shared/ui/index.ts
  src/stories/ChatInput.stories.tsx
  src/stories/LiveInfo.stories.ts
  src/widgets/chat/ChatInput.tsx
  src/widgets/chat/index.ts
  src/widgets/playlist/ActionBar.tsx
  src/widgets/playlist/ControlBar.tsx
  src/widgets/playlist/ProgressBar.tsx
  src/widgets/playlist/index.ts
Labels: HIGH

#53 [refactor] 둘러보기 UI 코드 리팩토링 및 세로 swipe 구현
  src/App.tsx
  src/assets/icons/icn_overlay.svg
  src/assets/icons/icn_share.svg
  src/assets/icons/index.ts
  src/assets/images/img_cd_overlay_test.png
  src/entities/playlist/model/types.ts
  src/features/like/index.ts
  src/features/like/model/useLike.ts
  src/features/share/index.ts
  src/features/share/ui/ShareButton.tsx
  src/features/swipe/index.ts
  src/features/swipe/ui/SwipeCarousel.tsx
  src/pages/discoverPage/index.tsx
  src/pages/discoverPage/mockData.json
  src/pages/homePage/index.tsx
  src/shared/config/navItems.ts
  src/shared/config/routesConfig.ts
  src/shared/ui/Cd.tsx
  src/shared/ui/LiveInfo.tsx
  src/shared/ui/index.ts
  src/stories/Cd.stories.tsx
  src/stories/LiveInfo.stories.tsx
  src/stories/NavBar.stories.ts
  src/stories/Playlist.stories.tsx
  src/widgets/layout/Footer.tsx
  src/widgets/layout/Header.tsx
  src/widgets/layout/NavBar.tsx
  src/widgets/layout/index.ts
  src/widgets/playlist/ActionBar.tsx
  src/widgets/playlist/Playlist.tsx
  src/widgets/playlist/PlaylistLayout.tsx
  src/widgets/playlist/index.ts
Labels: HIGH

#54 [refactor] 마이페이지 > 플레이리스트 추가 UI 코드 리팩토링
  index.html
  src/App.tsx
  src/assets/icons/icn_pencil_primary.svg
  src/assets/icons/index.ts
  src/assets/images/img_profile.png
  src/pages/customize/index.tsx
  src/pages/myPage/api/api.ts
  src/pages/myPage/hooks/hooks.ts
  src/pages/myPage/mock/likePlaylist.json
  src/pages/myPage/mock/likeUser.json
  src/pages/myPage/mock/playlistLinks.json
  src/pages/myPage/ui/components/CdGrid.tsx
  src/pages/myPage/ui/components/Divider.tsx
  src/pages/myPage/ui/components/index.ts
  src/pages/myPage/ui/create/components/LinkItem.tsx
  src/pages/myPage/ui/create/components/index.ts
  src/pages/myPage/ui/create/index.tsx
  src/pages/myPage/ui/index.tsx
  src/pages/myPage/ui/privacy/index.tsx
  src/pages/myPage/ui/terms/index.tsx
  src/pages/myPage/ui/unregister/index.tsx
  src/pages/searchPage/SearchResultPage.tsx
  src/pages/searchPage/ui/index.ts
  src/shared/config/musicGenres.ts
  src/shared/lib/useDevice.ts
  src/shared/lib/useSingleSelect.ts
  src/shared/styles/terms.ts
  src/shared/styles/theme.ts
  src/shared/ui/BottomSheet.tsx
  src/shared/ui/ContentHeader.tsx
  src/shared/ui/Input.tsx
  src/shared/ui/Loading.tsx
  src/shared/ui/Modal.tsx
  src/shared/ui/index.ts
  src/shared/utils/common.ts
  src/stories/ContentHeader.stories.tsx
  src/stories/Loading.stories.tsx
  src/stories/SearchResultItem.stories.tsx
  src/widgets/search/SearchResultItem.tsx
  src/widgets/search/index.ts
Labels: MEDIUM

#61 [feat] 공통 status 페이지/컴포넌트 UI 구현
  src/assets/icons/icn_error.svg
  src/assets/icons/icn_no_data.svg
  src/assets/icons/icn_not_found.svg
  src/assets/icons/index.ts
  src/pages/error/index.tsx
  src/pages/notFound/index.tsx
  src/shared/config/routesConfig.ts
  src/shared/styles/status.ts
  src/shared/ui/Error.tsx
  src/shared/ui/NoData.tsx
  src/shared/ui/NotFound.tsx
  src/shared/ui/index.ts
  src/stories/Error.stories.tsx
  src/stories/NoData.stories.tsx
  src/stories/NotFound.stories.tsx
Labels: MEDIUM

#62 [feat] 나의 CD 기능 및 Toast Message 구현
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/app/providers/ToastProvider.tsx
  src/app/providers/index.ts
  src/assets/icons/icn_coach.svg
  src/assets/icons/icn_toast_circle.svg
  src/assets/icons/index.ts
  src/assets/lottie/index.ts
  src/assets/lottie/swipe.json
  src/features/share/index.ts
  src/features/share/ui/ShareButton.tsx
  src/features/share/ui/ShareImage.tsx
  src/pages/discover/ui/DiscoverCoachMark.tsx
  src/pages/mycd/MyCdLayout.tsx
  src/pages/mycd/index.tsx
  src/pages/mycd/myPlaylist.json
  src/pages/mycd/playlist/index.tsx
  src/shared/config/routesConfig.ts
  src/shared/ui/Cd.tsx
  src/shared/ui/Toast.tsx
  src/shared/ui/index.ts
  src/stories/Toast.stories.tsx
  src/widgets/playlist/ActionBar.tsx
  src/widgets/playlist/PlaylistLayout.tsx
Labels: HIGH

#65 [feat] 로그인 UI 구현 및 API 연동 (#43)
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/icons/icn_kakao.svg
  src/assets/icons/index.ts
  src/features/auth/api/auth.ts
  src/features/auth/api/authApi.ts
  src/features/auth/index.ts
  src/features/auth/lib/pkce.ts
  src/features/auth/model/authStore.ts
  src/features/auth/model/useAuth.ts
  src/features/auth/store/authStore.ts
  src/features/auth/types/auth.ts
  src/features/auth/ui/AuthButton.tsx
  src/main.tsx
  src/pages/login/callback/index.tsx
  src/pages/login/index.tsx
  src/shared/api/instance.ts
  src/shared/config/routesConfig.ts
Labels: HIGH

#69 [feat] 플레이리스트 추천 API 연동
  src/assets/card/drive_lg.svg
  src/assets/card/index.ts
  src/assets/card/kpop_lg.svg
  src/assets/card/mood_lg.svg
  src/assets/card/party_lg.svg
  src/assets/card/relax_lg.svg
  src/assets/card/romance_lg.svg
  src/assets/card/sad_lg.svg
  src/assets/card/sleep_lg.svg
  src/assets/card/study_lg.svg
  src/assets/card/workout_lg.svg
  src/assets/icons/icn_character.svg
  src/assets/icons/index.ts
  src/assets/images/img_character.png
  src/entities/playlist/index.ts
  src/entities/playlist/model/types.ts
  src/features/recommend/api/recommend.ts
  src/features/recommend/index.ts
  src/features/recommend/model/useRecommend.ts
  src/features/recommend/types/recommend.ts
  src/features/search/types/search.ts
  src/pages/discover/index.tsx
  src/pages/discover/playlist/index.tsx
  src/pages/discover/playlistData.json
  src/pages/home/config/messages.ts
  src/pages/home/index.tsx
  src/pages/home/ui/DotButton.tsx
  src/pages/home/ui/LoopCarousel.tsx
  src/pages/home/ui/index.ts
  src/pages/mycd/index.tsx
  src/pages/mycd/myPlaylist.json
  src/pages/mycd/playlist/index.tsx
  src/pages/search/index.tsx
  src/shared/config/routesConfig.ts
  src/shared/ui/Link.tsx
  src/stories/Link.stories.ts
  src/stories/LoopCarousel.stories.tsx
  src/stories/PlaylistWithSong.stories.ts
  src/widgets/playlist/Playlist.tsx
  src/widgets/playlist/PlaylistLayout.tsx
  src/widgets/playlist/PlaylistWithSong.tsx
Labels: HIGH

#72 [feat] 둘러보기 + 채팅 API 연동
  package.json
  pnpm-lock.yaml
  src/app/providers/PlayerProvider.tsx
  src/assets/icons/icn_character.svg
  src/assets/icons/index.ts
  src/assets/images/img_character_guest.png
  src/assets/images/img_character_member.png
  src/assets/images/index.ts
  src/entities/comment/ui/Comment.tsx
  src/entities/playlist/api/playlist.ts
  src/entities/playlist/index.ts
  src/entities/playlist/model/types.ts
  src/entities/playlist/model/usePlaylists.ts
  src/entities/playlist/types/playlist.ts
  src/features/auth/api/auth.ts
  src/features/auth/model/useAuth.ts
  src/features/chat/api/chat.ts
  src/features/chat/index.ts
  src/features/chat/lib/chat.ts
  src/features/chat/model/sendMessage.ts
  src/features/chat/model/useChat.ts
  src/features/chat/types/chat.ts
  src/features/follow/api/follow.ts
  src/features/follow/index.ts
  src/features/follow/model/useFollow.ts
  src/features/follow/ui/FollowButton.tsx
  src/features/share/ui/ShareButton.tsx
  src/features/share/ui/ShareImage.tsx
  src/features/swipe/ui/SwipeCarousel.tsx
  src/pages/discover/index.tsx
  src/pages/discover/playlist/index.tsx
  src/pages/discover/playlistData.json
  src/pages/home/ui/LoopCarousel.tsx
  src/shared/api/httpClient.ts
  src/shared/lib/getGenreLabel.ts
  src/shared/lib/getVideoId.ts
  src/shared/lib/index.ts
  src/shared/ui/LiveInfo.tsx
  src/shared/ui/ScrollCarousel.tsx
  src/sockjs-client.d.ts
  src/widgets/chat/ChatBottomSheet.tsx
  src/widgets/chat/ChatButton.tsx
  src/widgets/chat/ChatInput.tsx
  src/widgets/chat/EmojiCarousel.tsx
  src/widgets/layout/NavBar.tsx
  src/widgets/playlist/ActionBar.tsx
  src/widgets/playlist/ControlBar.tsx
  src/widgets/playlist/PlaylistLayout.tsx
  src/widgets/playlist/PlaylistWithSong.tsx
  src/widgets/playlist/VolumeButton.tsx
  src/widgets/playlist/YoutubePlayer.tsx
Labels: HIGH

#78 [feat] 프로필 수정 api 연동
  src/app/providers/ToastProvider.tsx
  src/entities/playlist/api/playlist.ts
  src/entities/playlist/model/usePlaylists.ts
  src/features/auth/store/authStore.ts
  src/features/auth/types/auth.ts
  src/features/profile/api/profile.ts
  src/features/profile/model/useProfile.ts
  src/features/profile/types/profile.ts
  src/pages/login/index.tsx
  src/pages/myPage/ui/components/UserProfile.tsx
  src/pages/myPage/ui/customize/index.tsx
  src/pages/myPage/ui/playlist/index.tsx
  src/pages/mycd/playlist/index.tsx
  src/shared/api/instance.ts
  src/shared/config/routesConfig.ts
  src/shared/ui/Cd.tsx
  src/widgets/authGuard/PrivateRoute.tsx
  src/widgets/playlist/PlaylistHorizontal.tsx
Labels: HIGH

#87 [fix] discovery 셔플 이슈 해결
  src/entities/comment/ui/Comment.tsx
  src/entities/playlist/types/playlist.ts
  src/features/chat/api/chat.ts
  src/features/chat/model/sendMessage.ts
  src/features/chat/model/useChat.ts
  src/pages/discover/index.tsx
  src/pages/discover/ui/RedirectToShuffle.tsx
  src/shared/config/routesConfig.ts
  src/widgets/chat/ChatBottomSheet.tsx
  src/widgets/chat/ChatButton.tsx
  src/widgets/layout/NavBar.tsx
  src/widgets/playlist/ActionBar.tsx
  src/widgets/playlist/PlaylistLayout.tsx
Labels: HIGH

#91 [feat] 플레이리스트 수정 api 연동
  src/entities/playlist/model/useMyPlaylist.ts
  src/entities/playlist/types/playlist.ts
  src/features/customize/api/customize.ts
  src/features/customize/model/useCustomize.ts
  src/features/customize/types/customize.ts
  src/pages/myPage/lib/customizeTheme.ts
  src/pages/myPage/ui/components/CdGrid.tsx
  src/pages/myPage/ui/customize/index.tsx
  src/pages/myPage/ui/customize/step1/index.tsx
  src/pages/myPage/ui/customize/step2/index.tsx
  src/shared/config/routesConfig.ts
  src/shared/ui/Cd.tsx
Labels: HIGH

#95 [fix] 둘러보기 selectedIndex 오류 수정
  src/features/swipe/ui/SwipeCarousel.tsx
  src/pages/discover/index.tsx
  src/shared/ui/Cd.tsx
  src/widgets/chat/ChatBottomSheet.tsx
Labels: CRITICAL

#99 fix: gap 수정 (#94)
  src/pages/mycd/index.tsx
Labels: MEDIUM
